/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "Glance.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CustomScene, CustomScene, 4)


PB_BIND(CustomScene_Object, CustomScene_Object, 2)


PB_BIND(CustomScene_Object_AreaAnimationData, CustomScene_Object_AreaAnimationData, AUTO)


PB_BIND(CustomScene_Object_AreaAnimationData_LightFlashData, CustomScene_Object_AreaAnimationData_LightFlashData, AUTO)


PB_BIND(CustomScene_Object_AreaAnimationData_PulseData, CustomScene_Object_AreaAnimationData_PulseData, AUTO)


PB_BIND(CustomScene_Object_AreaAnimationData_WaveData, CustomScene_Object_AreaAnimationData_WaveData, AUTO)


PB_BIND(CustomScene_Object_CmdData, CustomScene_Object_CmdData, AUTO)


PB_BIND(CustomScene_Object_FillData, CustomScene_Object_FillData, AUTO)


PB_BIND(CustomScene_Object_GifData, CustomScene_Object_GifData, AUTO)


PB_BIND(CustomScene_Object_MovingBarData, CustomScene_Object_MovingBarData, AUTO)


PB_BIND(CustomScene_Object_WeatherData, CustomScene_Object_WeatherData, AUTO)


PB_BIND(Notice, Notice, 2)


PB_BIND(Segments, Segments, 4)


PB_BIND(Segments_Segment, Segments_Segment, 2)


PB_BIND(Settings, Settings, AUTO)


PB_BIND(Settings_DND, Settings_DND, AUTO)


PB_BIND(Settings_Silent, Settings_Silent, AUTO)


PB_BIND(TextData, TextData, AUTO)


PB_BIND(Timer, Timer, 2)


PB_BIND(Timer_Interval, Timer_Interval, 2)


PB_BIND(AlarmData, AlarmData, 2)


PB_BIND(AlarmData_Time, AlarmData_Time, AUTO)


PB_BIND(Alarms, Alarms, 2)


PB_BIND(ForecastScene, ForecastScene, AUTO)


PB_BIND(AppointmentsScene, AppointmentsScene, 2)



























