/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GLANCE_PB_H_INCLUDED
#define PB_GLANCE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Days {
    Days_None = 0,
    Days_Monday = 1,
    Days_Tuesday = 2,
    Days_Wednesday = 3,
    Days_Thursday = 4,
    Days_Friday = 5,
    Days_Saturday = 6,
    Days_Sunday = 7,
    Days_All = 8
} Days;

typedef enum _Animation {
    Animation_NoneAnimation = 0,
    Animation_Pulse = 1,
    Animation_Wave = 2,
    Animation_GifStart = 3,
    Animation_Fire = 10,
    Animation_Wheel = 11,
    Animation_Flower = 12,
    Animation_Flower2 = 13,
    Animation_Fan = 14,
    Animation_Sun = 15,
    Animation_Thunderstorm = 16,
    Animation_Cloud = 17,
    Animation_WeatherClear = 101,
    Animation_WeatherCloudy = 102,
    Animation_WeatherFog = 103,
    Animation_WeatherLightRain = 104,
    Animation_WeatherRain = 105,
    Animation_WeatherThunderstorm = 106,
    Animation_WeatherSnow = 107,
    Animation_WeatherHail = 108,
    Animation_WeatherWind = 109,
    Animation_WeatherTornado = 110,
    Animation_WeatherHurricane = 111,
    Animation_WeatherSnowThunderstorm = 112
} Animation;

typedef enum _Color {
    Color_Black = 0,
    Color_DarkGoldenRod = 1,
    Color_Darkorange = 2,
    Color_Olive = 3,
    Color_OrangeRed = 4,
    Color_Red = 5,
    Color_Maroon = 6,
    Color_DarkMagenta = 7,
    Color_MediumVioletRed = 8,
    Color_Brown = 9,
    Color_Indigo = 10,
    Color_BlueViolet = 11,
    Color_White = 12,
    Color_LightSlateBlue = 13,
    Color_RoyalBlue = 14,
    Color_Blue = 15,
    Color_CornflowerBlue = 16,
    Color_SkyBlue = 17,
    Color_Turquoise = 18,
    Color_Aqua = 19,
    Color_MediumSpringGreen = 20,
    Color_LimeGreen = 21,
    Color_DarkGreen = 22,
    Color_Lime = 23,
    Color_LawnGreen = 24,
    Color_Google1 = 25,
    Color_Google2 = 26,
    Color_Google3 = 27,
    Color_Google4 = 28,
    Color_Google5 = 29,
    Color_Google6 = 30,
    Color_Google7 = 31,
    Color_Google8 = 32,
    Color_Google9 = 33,
    Color_Google10 = 34,
    Color_Google11 = 35,
    Color_Google12 = 36,
    Color_Google13 = 37,
    Color_Google14 = 38,
    Color_Google15 = 39,
    Color_Google16 = 40,
    Color_Google17 = 41,
    Color_Google18 = 42,
    Color_Google19 = 43,
    Color_Google20 = 44,
    Color_Google21 = 45,
    Color_Google22 = 46,
    Color_Google23 = 47,
    Color_Google24 = 48,
    Color_Google25 = 49,
    Color_Google26 = 50,
    Color_Google27 = 51,
    Color_Google28 = 52,
    Color_Google29 = 53
} Color;

typedef enum _Sound {
    Sound_NoneSound = 0,
    Sound_Waves = 1, /* Also known as Alarm */
    Sound_Rise = 2, /* Also known as Calendar_alert */
    Sound_Charging = 3,
    Sound_Steps = 4, /* Also known as Fitness_alert */
    Sound_Radar = 5, /* Also known as General_alert_1 */
    Sound_Bells = 6, /* Also known as General_alert_2 */
    Sound_Bye = 7, /* Also known as Goodbye */
    Sound_Hello = 8,
    Sound_Flowers = 9, /* Also known as Ringtone */
    Sound_Circles = 10, /* Also known as Taxi */
    Sound_Complete = 11, /* Also known as Timer_end */
    Sound_Popcorn = 12, /* Also known as Weather_alert */
    Sound_Break = 13,
    Sound_Opening = 14,
    Sound_High = 15,
    Sound_Shine = 16,
    Sound_Extension = 17
} Sound;

typedef enum _CustomScene_Object_Method {
    CustomScene_Object_Method_Cmd = 1,
    CustomScene_Object_Method_Fill = 2,
    CustomScene_Object_Method_Sound = 3,
    CustomScene_Object_Method_Text = 4,
    CustomScene_Object_Method_MovingBar = 5,
    CustomScene_Object_Method_AreaAnimation = 7,
    CustomScene_Object_Method_Gif = 8,
    CustomScene_Object_Method_Weather = 9
} CustomScene_Object_Method;

typedef enum _CustomScene_Object_Result { /* TODO: Find out the meaning of these */
    CustomScene_Object_Result_OK = 0, /* Everything drawn will stay (albeit inanimate) after its lifeTime is over */
    CustomScene_Object_Result_SaveTime = 1,
    CustomScene_Object_Result_BackTime = 2,
    CustomScene_Object_Result_DelTime = 3,
    CustomScene_Object_Result_Expired = 4, /* Everything drawn will vanish after its lifeTime is over */
    CustomScene_Object_Result_End = 5, /* The whole scene will end after its lifeTime is over */
    CustomScene_Object_Result_NewSeq = 6
} CustomScene_Object_Result;

typedef enum _CustomScene_Object_AreaAnimationData_Type {
    CustomScene_Object_AreaAnimationData_Type_TypePulse = 0,
    CustomScene_Object_AreaAnimationData_Type_TypeWave = 1,
    CustomScene_Object_AreaAnimationData_Type_LightFlash = 2
} CustomScene_Object_AreaAnimationData_Type;

typedef enum _CustomScene_Object_WeatherData_Condition {
    CustomScene_Object_WeatherData_Condition_Snow = 0,
    CustomScene_Object_WeatherData_Condition_Rain = 1,
    CustomScene_Object_WeatherData_Condition_Fog = 2
} CustomScene_Object_WeatherData_Condition;

typedef enum _CustomScene_Object_WeatherData_Position {
    CustomScene_Object_WeatherData_Position_FullScreen = 0,
    CustomScene_Object_WeatherData_Position_UpperHalf = 1,
    CustomScene_Object_WeatherData_Position_DownHalf = 2
} CustomScene_Object_WeatherData_Position;

typedef enum _Settings_DateFormat {
    Settings_DateFormat_DateDisabled = 0,
    Settings_DateFormat_Date24Jan = 1,
    Settings_DateFormat_Date24Tue = 2,
    Settings_DateFormat_DateJan24 = 3,
    Settings_DateFormat_DateTue24 = 4
} Settings_DateFormat;

typedef enum _TextData_Modificator {
    TextData_Modificator_ModNone = 0,
    TextData_Modificator_Repeat = 1,
    TextData_Modificator_Rapid = 2,
    TextData_Modificator_Delay = 3
} TextData_Modificator;

typedef enum _AppointmentsScene_Notify {
    AppointmentsScene_Notify_DISABLED = 0,
    AppointmentsScene_Notify_ENABLED = 1
} AppointmentsScene_Notify;

/* Struct definitions */
typedef struct _CustomScene_Object_AreaAnimationData_LightFlashData {
    bool has_color;
    Color color;
    bool has_speed;
    int32_t speed;
} CustomScene_Object_AreaAnimationData_LightFlashData;

typedef struct _CustomScene_Object_AreaAnimationData_PulseData {
    bool has_riseTime;
    int32_t riseTime;
    bool has_fallTime;
    int32_t fallTime;
} CustomScene_Object_AreaAnimationData_PulseData;

typedef struct _CustomScene_Object_AreaAnimationData_WaveData {
    bool has_speed;
    int32_t speed;
} CustomScene_Object_AreaAnimationData_WaveData;

typedef struct _CustomScene_Object_AreaAnimationData { /* This gets layered onto already drawn areas
you draw some areas using MovingBarData and then apply an effect to the same area with this */
    CustomScene_Object_AreaAnimationData_Type type;
    pb_size_t area_count;
    int32_t area[24];
    bool has_wave;
    CustomScene_Object_AreaAnimationData_WaveData wave;
    bool has_pulse;
    CustomScene_Object_AreaAnimationData_PulseData pulse;
    bool has_flashLight;
    CustomScene_Object_AreaAnimationData_LightFlashData flashLight;
} CustomScene_Object_AreaAnimationData;

typedef PB_BYTES_ARRAY_T(32) CustomScene_Object_CmdData_data_t;
typedef struct _CustomScene_Object_CmdData {
    /* Yeah good luck figuring that out without access to either messages or the firmware sourcecode */
    CustomScene_Object_CmdData_data_t data;
} CustomScene_Object_CmdData;

typedef struct _CustomScene_Object_FillData {
    pb_size_t segment_count;
    int32_t segment[48];
} CustomScene_Object_FillData;

typedef struct _CustomScene_Object_GifData {
    Animation type; /* This only accepts a subset of the animation Enum: 10 - 17 */
    bool has_segment;
    int32_t segment; /* As length in pixels, only multiples of 8 (-1, due to there already being at least one px) work.
Everything else will be rounded down to the previous multiple of 8 by the clock
Also, the height property doesn't have any effect */
    bool has_speed;
    int32_t speed; /* 0 to 10 */
} CustomScene_Object_GifData;

typedef struct _CustomScene_Object_MovingBarData {
    int32_t area; /* Pixel 0-47 */
    bool has_frontColor;
    Color frontColor;
    bool has_backColor;
    Color backColor;
    bool has_speed;
    int32_t speed; /* -10 to 10 (Controls direction & speed) */
} CustomScene_Object_MovingBarData;

typedef struct _CustomScene_Object_WeatherData {
    CustomScene_Object_WeatherData_Condition condition;
    bool has_position;
    CustomScene_Object_WeatherData_Position position;
    bool has_intensity;
    int32_t intensity; /* 0 to 10 */
} CustomScene_Object_WeatherData;

typedef struct _Settings_DND {
    bool recurring;
    int32_t fromHour;
    int32_t tillHour;
} Settings_DND;

typedef struct _Settings_Silent {
    bool recurring;
    int32_t fromHour;
    int32_t tillHour;
} Settings_Silent;

typedef struct _Settings { /* TODO defaults */
    bool has_dnd;
    Settings_DND dnd;
    bool has_nightModeEnabled;
    bool nightModeEnabled;
    bool has_permanentDND;
    bool permanentDND;
    bool has_permanentMute;
    bool permanentMute;
    bool has_dateFormat;
    Settings_DateFormat dateFormat;
    bool has_mgrSilentIntervalMin;
    int32_t mgrSilentIntervalMin;
    bool has_mgrSilentIntervalMax;
    int32_t mgrSilentIntervalMax;
    bool has_pointsAlwaysEnabled;
    bool pointsAlwaysEnabled;
    bool has_displayBrightness;
    int32_t displayBrightness;
    bool has_timeModeEnable;
    bool timeModeEnable;
    bool has_timeFormat12;
    bool timeFormat12;
    bool has_mgrUserActivityTimeout;
    int32_t mgrUserActivityTimeout;
    bool has_silent;
    Settings_Silent silent;
} Settings;

typedef PB_BYTES_ARRAY_T(64) TextData_text_t;
typedef struct _TextData {
    bool has_modificators;
    TextData_Modificator modificators;
    TextData_text_t text; /* Each byte is an ascii charcode */
} TextData;

typedef struct _CustomScene_Object {
    CustomScene_Object_Method method;
    bool has_startTime;
    int32_t startTime;
    int32_t lifeTime;
    bool has_result;
    CustomScene_Object_Result result;
    bool has_areaAnimation;
    CustomScene_Object_AreaAnimationData areaAnimation;
    bool has_fill;
    CustomScene_Object_FillData fill;
    pb_size_t text_count;
    TextData text[4];
    bool has_sound;
    Sound sound;
    bool has_movingBar;
    CustomScene_Object_MovingBarData movingBar;
    bool has_cmd;
    CustomScene_Object_CmdData cmd;
    bool has_gif;
    CustomScene_Object_GifData gif;
    bool has_weather;
    CustomScene_Object_WeatherData weather;
} CustomScene_Object;

/* This is most likely the data structure which got generated by the glance backend
if you had an api key and sent custom scenes */
typedef struct _CustomScene {
    pb_size_t object_count;
    CustomScene_Object object[16]; /* This represents a sequence of things where each thing is an object
The sequence in which they are contained here doesn't specify when they are displayed though
instead, their visibility depends on their startTime and lifeTime property */
} CustomScene;

typedef struct _Notice {
    bool has_type;
    Animation type;
    bool has_sound;
    Sound sound;
    bool has_color;
    Color color;
    pb_size_t text_count;
    TextData text[4];
} Notice;

typedef struct _Segments_Segment {
    int32_t segment;
    pb_size_t text_count;
    TextData text[4];
} Segments_Segment;

typedef struct _Segments {
    pb_size_t segments_count;
    Segments_Segment segments[16];
    bool has_sound;
    Sound sound;
} Segments;

typedef struct _Timer_Interval {
    pb_size_t text_count;
    TextData text[4]; /* Valid, but not used at all? */
    int32_t duration; /* Seconds */
    bool has_countdown;
    int32_t countdown; /* Seconds */
} Timer_Interval;

typedef struct _Timer {
    bool has_countdown;
    int32_t countdown; /* Pre-timer countdown. */
    pb_size_t intervals_count;
    Timer_Interval intervals[8];
    pb_size_t finalText_count;
    TextData finalText[4];
} Timer;

typedef struct _AlarmData_Time {
    int32_t hours;
    int32_t minutes;
} AlarmData_Time;

typedef struct _AlarmData {
    bool has_enabled;
    bool enabled;
    bool has_days;
    int32_t days;
    AlarmData_Time time;
    Sound sound;
    pb_size_t text_count;
    TextData text[4];
} AlarmData;

typedef struct _Alarms {
    pb_size_t alarm_count;
    AlarmData alarm[8];
} Alarms;

typedef PB_BYTES_ARRAY_T(48) ForecastScene_values_t;
typedef PB_BYTES_ARRAY_T(64) ForecastScene_templateText_t;
typedef struct _ForecastScene {
    int64_t timestamp; /* A unix timestamp
This has to be localtime so its not _really_ a UTC-based unix timestamp
due to the fact that everything this clock expects is localtime */
    bool has_doNotChange;
    uint32_t doNotChange; /* Absolutely no idea. */
    int32_t maxColor; /* RGB FFFFFF = white */
    int32_t minColor;
    int32_t max;
    int32_t min; /* The clock will use these to draw the circle from the values in "values" */
    ForecastScene_values_t values; /* 24 Int16LE. Each representing the forecasted value for one time unit (1h)
starting at timestamp. Valid for 24h
The clock will smoothen it automatically, so you can't have quickly alternating data.
Well.. you can, but it will end up as a star pattern which looks pretty nice actually */
    ForecastScene_templateText_t templateText; /* 0x08 will be replaced with the current value from values which is valid at this moment
It can appear multiple times. All appearances will be replaced
To write an icon, it has to be prefixed with 0xC2. e.g. 0xC2,0xB0 for °
Regular ascii codes can be used
Example template: 0xC2,0x8F,0x08,0xC2,0xB0 = "[Thermometer icon][Current Value]°" */
} ForecastScene;

typedef PB_BYTES_ARRAY_T(512) AppointmentsScene_appointmentData_t;
typedef struct _AppointmentsScene {
    int64_t timestamp; /* A unix timestamp;
This probably also has to be localtime so its not _really_ a UTC-based unix timestamp
due to the fact that everything this clock expects is localtime */
    AppointmentsScene_appointmentData_t appointmentData; /* I don't really understand the format, sadly. It seems like I'm missing something important
I've added sample appointment messages to this reposity so if you feel like looking into this further go ahead
sample_appointments.js */
    pb_size_t appointmentNames_count;
    TextData appointmentNames[16];
    AppointmentsScene_Notify notify;
    Sound sound;
} AppointmentsScene;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Days_MIN Days_None
#define _Days_MAX Days_All
#define _Days_ARRAYSIZE ((Days)(Days_All+1))

#define _Animation_MIN Animation_NoneAnimation
#define _Animation_MAX Animation_WeatherSnowThunderstorm
#define _Animation_ARRAYSIZE ((Animation)(Animation_WeatherSnowThunderstorm+1))

#define _Color_MIN Color_Black
#define _Color_MAX Color_Google29
#define _Color_ARRAYSIZE ((Color)(Color_Google29+1))

#define _Sound_MIN Sound_NoneSound
#define _Sound_MAX Sound_Extension
#define _Sound_ARRAYSIZE ((Sound)(Sound_Extension+1))

#define _CustomScene_Object_Method_MIN CustomScene_Object_Method_Cmd
#define _CustomScene_Object_Method_MAX CustomScene_Object_Method_Weather
#define _CustomScene_Object_Method_ARRAYSIZE ((CustomScene_Object_Method)(CustomScene_Object_Method_Weather+1))

#define _CustomScene_Object_Result_MIN CustomScene_Object_Result_OK
#define _CustomScene_Object_Result_MAX CustomScene_Object_Result_NewSeq
#define _CustomScene_Object_Result_ARRAYSIZE ((CustomScene_Object_Result)(CustomScene_Object_Result_NewSeq+1))

#define _CustomScene_Object_AreaAnimationData_Type_MIN CustomScene_Object_AreaAnimationData_Type_TypePulse
#define _CustomScene_Object_AreaAnimationData_Type_MAX CustomScene_Object_AreaAnimationData_Type_LightFlash
#define _CustomScene_Object_AreaAnimationData_Type_ARRAYSIZE ((CustomScene_Object_AreaAnimationData_Type)(CustomScene_Object_AreaAnimationData_Type_LightFlash+1))

#define _CustomScene_Object_WeatherData_Condition_MIN CustomScene_Object_WeatherData_Condition_Snow
#define _CustomScene_Object_WeatherData_Condition_MAX CustomScene_Object_WeatherData_Condition_Fog
#define _CustomScene_Object_WeatherData_Condition_ARRAYSIZE ((CustomScene_Object_WeatherData_Condition)(CustomScene_Object_WeatherData_Condition_Fog+1))

#define _CustomScene_Object_WeatherData_Position_MIN CustomScene_Object_WeatherData_Position_FullScreen
#define _CustomScene_Object_WeatherData_Position_MAX CustomScene_Object_WeatherData_Position_DownHalf
#define _CustomScene_Object_WeatherData_Position_ARRAYSIZE ((CustomScene_Object_WeatherData_Position)(CustomScene_Object_WeatherData_Position_DownHalf+1))

#define _Settings_DateFormat_MIN Settings_DateFormat_DateDisabled
#define _Settings_DateFormat_MAX Settings_DateFormat_DateTue24
#define _Settings_DateFormat_ARRAYSIZE ((Settings_DateFormat)(Settings_DateFormat_DateTue24+1))

#define _TextData_Modificator_MIN TextData_Modificator_ModNone
#define _TextData_Modificator_MAX TextData_Modificator_Delay
#define _TextData_Modificator_ARRAYSIZE ((TextData_Modificator)(TextData_Modificator_Delay+1))

#define _AppointmentsScene_Notify_MIN AppointmentsScene_Notify_DISABLED
#define _AppointmentsScene_Notify_MAX AppointmentsScene_Notify_ENABLED
#define _AppointmentsScene_Notify_ARRAYSIZE ((AppointmentsScene_Notify)(AppointmentsScene_Notify_ENABLED+1))


#define CustomScene_Object_method_ENUMTYPE CustomScene_Object_Method
#define CustomScene_Object_result_ENUMTYPE CustomScene_Object_Result
#define CustomScene_Object_sound_ENUMTYPE Sound

#define CustomScene_Object_AreaAnimationData_type_ENUMTYPE CustomScene_Object_AreaAnimationData_Type

#define CustomScene_Object_AreaAnimationData_LightFlashData_color_ENUMTYPE Color





#define CustomScene_Object_GifData_type_ENUMTYPE Animation

#define CustomScene_Object_MovingBarData_frontColor_ENUMTYPE Color
#define CustomScene_Object_MovingBarData_backColor_ENUMTYPE Color

#define CustomScene_Object_WeatherData_condition_ENUMTYPE CustomScene_Object_WeatherData_Condition
#define CustomScene_Object_WeatherData_position_ENUMTYPE CustomScene_Object_WeatherData_Position

#define Notice_type_ENUMTYPE Animation
#define Notice_sound_ENUMTYPE Sound
#define Notice_color_ENUMTYPE Color

#define Segments_sound_ENUMTYPE Sound


#define Settings_dateFormat_ENUMTYPE Settings_DateFormat



#define TextData_modificators_ENUMTYPE TextData_Modificator



#define AlarmData_sound_ENUMTYPE Sound




#define AppointmentsScene_notify_ENUMTYPE AppointmentsScene_Notify
#define AppointmentsScene_sound_ENUMTYPE Sound


/* Initializer values for message structs */
#define CustomScene_init_default                 {0, {CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default, CustomScene_Object_init_default}}
#define CustomScene_Object_init_default          {CustomScene_Object_Method_Fill, false, 0, 1, false, CustomScene_Object_Result_OK, false, CustomScene_Object_AreaAnimationData_init_default, false, CustomScene_Object_FillData_init_default, 0, {TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default}, false, Sound_NoneSound, false, CustomScene_Object_MovingBarData_init_default, false, CustomScene_Object_CmdData_init_default, false, CustomScene_Object_GifData_init_default, false, CustomScene_Object_WeatherData_init_default}
#define CustomScene_Object_AreaAnimationData_init_default {CustomScene_Object_AreaAnimationData_Type_TypePulse, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, CustomScene_Object_AreaAnimationData_WaveData_init_default, false, CustomScene_Object_AreaAnimationData_PulseData_init_default, false, CustomScene_Object_AreaAnimationData_LightFlashData_init_default}
#define CustomScene_Object_AreaAnimationData_LightFlashData_init_default {false, Color_White, false, 1}
#define CustomScene_Object_AreaAnimationData_PulseData_init_default {false, 50, false, 50}
#define CustomScene_Object_AreaAnimationData_WaveData_init_default {false, 1}
#define CustomScene_Object_CmdData_init_default  {{0, {0}}}
#define CustomScene_Object_FillData_init_default {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define CustomScene_Object_GifData_init_default  {Animation_GifStart, false, 782080, false, 3}
#define CustomScene_Object_MovingBarData_init_default {0, false, Color_Blue, false, Color_White, false, 0}
#define CustomScene_Object_WeatherData_init_default {CustomScene_Object_WeatherData_Condition_Snow, false, CustomScene_Object_WeatherData_Position_FullScreen, false, 5}
#define Notice_init_default                      {false, Animation_Pulse, false, Sound_Radar, false, Color_Lime, 0, {TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default}}
#define Segments_init_default                    {0, {Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default, Segments_Segment_init_default}, false, Sound_Rise}
#define Segments_Segment_init_default            {0, 0, {TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default}}
#define Settings_init_default                    {false, Settings_DND_init_default, false, true, false, false, false, false, false, Settings_DateFormat_DateDisabled, false, 0, false, 0, false, false, false, 0, false, true, false, false, false, 600, false, Settings_Silent_init_default}
#define Settings_DND_init_default                {false, 0, 0}
#define Settings_Silent_init_default             {0, 0, 0}
#define TextData_init_default                    {false, TextData_Modificator_Repeat, {0, {0}}}
#define Timer_init_default                       {false, 0, 0, {Timer_Interval_init_default, Timer_Interval_init_default, Timer_Interval_init_default, Timer_Interval_init_default, Timer_Interval_init_default, Timer_Interval_init_default, Timer_Interval_init_default, Timer_Interval_init_default}, 0, {TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default}}
#define Timer_Interval_init_default              {0, {TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default}, 0, false, 0}
#define AlarmData_init_default                   {false, true, false, 0, AlarmData_Time_init_default, Sound_NoneSound, 0, {TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default}}
#define AlarmData_Time_init_default              {0, 0}
#define Alarms_init_default                      {0, {AlarmData_init_default, AlarmData_init_default, AlarmData_init_default, AlarmData_init_default, AlarmData_init_default, AlarmData_init_default, AlarmData_init_default, AlarmData_init_default}}
#define ForecastScene_init_default               {0, false, 0u, 0, 0, 0, 0, {0, {0}}, {0, {0}}}
#define AppointmentsScene_init_default           {0, {0, {0}}, 0, {TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default, TextData_init_default}, _AppointmentsScene_Notify_MIN, _Sound_MIN}
#define CustomScene_init_zero                    {0, {CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero, CustomScene_Object_init_zero}}
#define CustomScene_Object_init_zero             {_CustomScene_Object_Method_MIN, false, 0, 0, false, _CustomScene_Object_Result_MIN, false, CustomScene_Object_AreaAnimationData_init_zero, false, CustomScene_Object_FillData_init_zero, 0, {TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero}, false, _Sound_MIN, false, CustomScene_Object_MovingBarData_init_zero, false, CustomScene_Object_CmdData_init_zero, false, CustomScene_Object_GifData_init_zero, false, CustomScene_Object_WeatherData_init_zero}
#define CustomScene_Object_AreaAnimationData_init_zero {_CustomScene_Object_AreaAnimationData_Type_MIN, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, CustomScene_Object_AreaAnimationData_WaveData_init_zero, false, CustomScene_Object_AreaAnimationData_PulseData_init_zero, false, CustomScene_Object_AreaAnimationData_LightFlashData_init_zero}
#define CustomScene_Object_AreaAnimationData_LightFlashData_init_zero {false, _Color_MIN, false, 0}
#define CustomScene_Object_AreaAnimationData_PulseData_init_zero {false, 0, false, 0}
#define CustomScene_Object_AreaAnimationData_WaveData_init_zero {false, 0}
#define CustomScene_Object_CmdData_init_zero     {{0, {0}}}
#define CustomScene_Object_FillData_init_zero    {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define CustomScene_Object_GifData_init_zero     {_Animation_MIN, false, 0, false, 0}
#define CustomScene_Object_MovingBarData_init_zero {0, false, _Color_MIN, false, _Color_MIN, false, 0}
#define CustomScene_Object_WeatherData_init_zero {_CustomScene_Object_WeatherData_Condition_MIN, false, _CustomScene_Object_WeatherData_Position_MIN, false, 0}
#define Notice_init_zero                         {false, _Animation_MIN, false, _Sound_MIN, false, _Color_MIN, 0, {TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero}}
#define Segments_init_zero                       {0, {Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero, Segments_Segment_init_zero}, false, _Sound_MIN}
#define Segments_Segment_init_zero               {0, 0, {TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero}}
#define Settings_init_zero                       {false, Settings_DND_init_zero, false, 0, false, 0, false, 0, false, _Settings_DateFormat_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, Settings_Silent_init_zero}
#define Settings_DND_init_zero                   {0, 0, 0}
#define Settings_Silent_init_zero                {0, 0, 0}
#define TextData_init_zero                       {false, _TextData_Modificator_MIN, {0, {0}}}
#define Timer_init_zero                          {false, 0, 0, {Timer_Interval_init_zero, Timer_Interval_init_zero, Timer_Interval_init_zero, Timer_Interval_init_zero, Timer_Interval_init_zero, Timer_Interval_init_zero, Timer_Interval_init_zero, Timer_Interval_init_zero}, 0, {TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero}}
#define Timer_Interval_init_zero                 {0, {TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero}, 0, false, 0}
#define AlarmData_init_zero                      {false, 0, false, 0, AlarmData_Time_init_zero, _Sound_MIN, 0, {TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero}}
#define AlarmData_Time_init_zero                 {0, 0}
#define Alarms_init_zero                         {0, {AlarmData_init_zero, AlarmData_init_zero, AlarmData_init_zero, AlarmData_init_zero, AlarmData_init_zero, AlarmData_init_zero, AlarmData_init_zero, AlarmData_init_zero}}
#define ForecastScene_init_zero                  {0, false, 0, 0, 0, 0, 0, {0, {0}}, {0, {0}}}
#define AppointmentsScene_init_zero              {0, {0, {0}}, 0, {TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero, TextData_init_zero}, _AppointmentsScene_Notify_MIN, _Sound_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define CustomScene_Object_AreaAnimationData_LightFlashData_color_tag 1
#define CustomScene_Object_AreaAnimationData_LightFlashData_speed_tag 2
#define CustomScene_Object_AreaAnimationData_PulseData_riseTime_tag 1
#define CustomScene_Object_AreaAnimationData_PulseData_fallTime_tag 2
#define CustomScene_Object_AreaAnimationData_WaveData_speed_tag 3
#define CustomScene_Object_AreaAnimationData_type_tag 1
#define CustomScene_Object_AreaAnimationData_area_tag 2
#define CustomScene_Object_AreaAnimationData_wave_tag 3
#define CustomScene_Object_AreaAnimationData_pulse_tag 4
#define CustomScene_Object_AreaAnimationData_flashLight_tag 5
#define CustomScene_Object_CmdData_data_tag      1
#define CustomScene_Object_FillData_segment_tag  1
#define CustomScene_Object_GifData_type_tag      1
#define CustomScene_Object_GifData_segment_tag   2
#define CustomScene_Object_GifData_speed_tag     3
#define CustomScene_Object_MovingBarData_area_tag 1
#define CustomScene_Object_MovingBarData_frontColor_tag 2
#define CustomScene_Object_MovingBarData_backColor_tag 3
#define CustomScene_Object_MovingBarData_speed_tag 4
#define CustomScene_Object_WeatherData_condition_tag 1
#define CustomScene_Object_WeatherData_position_tag 2
#define CustomScene_Object_WeatherData_intensity_tag 3
#define Settings_DND_recurring_tag               1
#define Settings_DND_fromHour_tag                2
#define Settings_DND_tillHour_tag                3
#define Settings_Silent_recurring_tag            1
#define Settings_Silent_fromHour_tag             2
#define Settings_Silent_tillHour_tag             3
#define Settings_dnd_tag                         1
#define Settings_nightModeEnabled_tag            2
#define Settings_permanentDND_tag                3
#define Settings_permanentMute_tag               4
#define Settings_dateFormat_tag                  5
#define Settings_mgrSilentIntervalMin_tag        6
#define Settings_mgrSilentIntervalMax_tag        7
#define Settings_pointsAlwaysEnabled_tag         9
#define Settings_displayBrightness_tag           10
#define Settings_timeModeEnable_tag              11
#define Settings_timeFormat12_tag                12
#define Settings_mgrUserActivityTimeout_tag      13
#define Settings_silent_tag                      14
#define TextData_modificators_tag                1
#define TextData_text_tag                        2
#define CustomScene_Object_method_tag            1
#define CustomScene_Object_startTime_tag         2
#define CustomScene_Object_lifeTime_tag          3
#define CustomScene_Object_result_tag            4
#define CustomScene_Object_areaAnimation_tag     5
#define CustomScene_Object_fill_tag              6
#define CustomScene_Object_text_tag              7
#define CustomScene_Object_sound_tag             8
#define CustomScene_Object_movingBar_tag         9
#define CustomScene_Object_cmd_tag               11
#define CustomScene_Object_gif_tag               12
#define CustomScene_Object_weather_tag           13
#define CustomScene_object_tag                   1
#define Notice_type_tag                          1
#define Notice_sound_tag                         2
#define Notice_color_tag                         3
#define Notice_text_tag                          4
#define Segments_Segment_segment_tag             1
#define Segments_Segment_text_tag                2
#define Segments_segments_tag                    1
#define Segments_sound_tag                       2
#define Timer_Interval_text_tag                  1
#define Timer_Interval_duration_tag              2
#define Timer_Interval_countdown_tag             3
#define Timer_countdown_tag                      1
#define Timer_intervals_tag                      2
#define Timer_finalText_tag                      3
#define AlarmData_Time_hours_tag                 1
#define AlarmData_Time_minutes_tag               2
#define AlarmData_enabled_tag                    2
#define AlarmData_days_tag                       3
#define AlarmData_time_tag                       4
#define AlarmData_sound_tag                      5
#define AlarmData_text_tag                       6
#define Alarms_alarm_tag                         1
#define ForecastScene_timestamp_tag              1
#define ForecastScene_doNotChange_tag            2
#define ForecastScene_maxColor_tag               4
#define ForecastScene_minColor_tag               5
#define ForecastScene_max_tag                    6
#define ForecastScene_min_tag                    7
#define ForecastScene_values_tag                 8
#define ForecastScene_templateText_tag           9
#define AppointmentsScene_timestamp_tag          1
#define AppointmentsScene_appointmentData_tag    2
#define AppointmentsScene_appointmentNames_tag   3
#define AppointmentsScene_notify_tag             6
#define AppointmentsScene_sound_tag              7

/* Struct field encoding specification for nanopb */
#define CustomScene_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  object,            1)
#define CustomScene_CALLBACK NULL
#define CustomScene_DEFAULT NULL
#define CustomScene_object_MSGTYPE CustomScene_Object

#define CustomScene_Object_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    method,            1) \
X(a, STATIC,   OPTIONAL, INT32,    startTime,         2) \
X(a, STATIC,   REQUIRED, INT32,    lifeTime,          3) \
X(a, STATIC,   OPTIONAL, UENUM,    result,            4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  areaAnimation,     5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fill,              6) \
X(a, STATIC,   REPEATED, MESSAGE,  text,              7) \
X(a, STATIC,   OPTIONAL, UENUM,    sound,             8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  movingBar,         9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cmd,              11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gif,              12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  weather,          13)
#define CustomScene_Object_CALLBACK NULL
#define CustomScene_Object_DEFAULT (const pb_byte_t*)"\x08\x02\x10\x00\x18\x01\x00"
#define CustomScene_Object_areaAnimation_MSGTYPE CustomScene_Object_AreaAnimationData
#define CustomScene_Object_fill_MSGTYPE CustomScene_Object_FillData
#define CustomScene_Object_text_MSGTYPE TextData
#define CustomScene_Object_movingBar_MSGTYPE CustomScene_Object_MovingBarData
#define CustomScene_Object_cmd_MSGTYPE CustomScene_Object_CmdData
#define CustomScene_Object_gif_MSGTYPE CustomScene_Object_GifData
#define CustomScene_Object_weather_MSGTYPE CustomScene_Object_WeatherData

#define CustomScene_Object_AreaAnimationData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, STATIC,   REPEATED, INT32,    area,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  wave,              3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pulse,             4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  flashLight,        5)
#define CustomScene_Object_AreaAnimationData_CALLBACK NULL
#define CustomScene_Object_AreaAnimationData_DEFAULT NULL
#define CustomScene_Object_AreaAnimationData_wave_MSGTYPE CustomScene_Object_AreaAnimationData_WaveData
#define CustomScene_Object_AreaAnimationData_pulse_MSGTYPE CustomScene_Object_AreaAnimationData_PulseData
#define CustomScene_Object_AreaAnimationData_flashLight_MSGTYPE CustomScene_Object_AreaAnimationData_LightFlashData

#define CustomScene_Object_AreaAnimationData_LightFlashData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    color,             1) \
X(a, STATIC,   OPTIONAL, INT32,    speed,             2)
#define CustomScene_Object_AreaAnimationData_LightFlashData_CALLBACK NULL
#define CustomScene_Object_AreaAnimationData_LightFlashData_DEFAULT (const pb_byte_t*)"\x08\x0c\x10\x01\x00"

#define CustomScene_Object_AreaAnimationData_PulseData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    riseTime,          1) \
X(a, STATIC,   OPTIONAL, INT32,    fallTime,          2)
#define CustomScene_Object_AreaAnimationData_PulseData_CALLBACK NULL
#define CustomScene_Object_AreaAnimationData_PulseData_DEFAULT (const pb_byte_t*)"\x08\x32\x10\x32\x00"

#define CustomScene_Object_AreaAnimationData_WaveData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    speed,             3)
#define CustomScene_Object_AreaAnimationData_WaveData_CALLBACK NULL
#define CustomScene_Object_AreaAnimationData_WaveData_DEFAULT (const pb_byte_t*)"\x18\x01\x00"

#define CustomScene_Object_CmdData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    data,              1)
#define CustomScene_Object_CmdData_CALLBACK NULL
#define CustomScene_Object_CmdData_DEFAULT NULL

#define CustomScene_Object_FillData_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, INT32,    segment,           1)
#define CustomScene_Object_FillData_CALLBACK NULL
#define CustomScene_Object_FillData_DEFAULT NULL

#define CustomScene_Object_GifData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, INT32,    segment,           2) \
X(a, STATIC,   OPTIONAL, INT32,    speed,             3)
#define CustomScene_Object_GifData_CALLBACK NULL
#define CustomScene_Object_GifData_DEFAULT (const pb_byte_t*)"\x08\x03\x10\x80\xde\x2f\x18\x03\x00"

#define CustomScene_Object_MovingBarData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    area,              1) \
X(a, STATIC,   OPTIONAL, UENUM,    frontColor,        2) \
X(a, STATIC,   OPTIONAL, UENUM,    backColor,         3) \
X(a, STATIC,   OPTIONAL, INT32,    speed,             4)
#define CustomScene_Object_MovingBarData_CALLBACK NULL
#define CustomScene_Object_MovingBarData_DEFAULT (const pb_byte_t*)"\x08\x00\x10\x0f\x18\x0c\x20\x00\x00"

#define CustomScene_Object_WeatherData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    condition,         1) \
X(a, STATIC,   OPTIONAL, UENUM,    position,          2) \
X(a, STATIC,   OPTIONAL, INT32,    intensity,         3)
#define CustomScene_Object_WeatherData_CALLBACK NULL
#define CustomScene_Object_WeatherData_DEFAULT (const pb_byte_t*)"\x18\x05\x00"

#define Notice_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, UENUM,    sound,             2) \
X(a, STATIC,   OPTIONAL, UENUM,    color,             3) \
X(a, STATIC,   REPEATED, MESSAGE,  text,              4)
#define Notice_CALLBACK NULL
#define Notice_DEFAULT (const pb_byte_t*)"\x08\x01\x10\x05\x18\x17\x00"
#define Notice_text_MSGTYPE TextData

#define Segments_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  segments,          1) \
X(a, STATIC,   OPTIONAL, UENUM,    sound,             2)
#define Segments_CALLBACK NULL
#define Segments_DEFAULT (const pb_byte_t*)"\x10\x02\x00"
#define Segments_segments_MSGTYPE Segments_Segment

#define Segments_Segment_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    segment,           1) \
X(a, STATIC,   REPEATED, MESSAGE,  text,              2)
#define Segments_Segment_CALLBACK NULL
#define Segments_Segment_DEFAULT (const pb_byte_t*)"\x08\x00\x00"
#define Segments_Segment_text_MSGTYPE TextData

#define Settings_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  dnd,               1) \
X(a, STATIC,   OPTIONAL, BOOL,     nightModeEnabled,   2) \
X(a, STATIC,   OPTIONAL, BOOL,     permanentDND,      3) \
X(a, STATIC,   OPTIONAL, BOOL,     permanentMute,     4) \
X(a, STATIC,   OPTIONAL, UENUM,    dateFormat,        5) \
X(a, STATIC,   OPTIONAL, INT32,    mgrSilentIntervalMin,   6) \
X(a, STATIC,   OPTIONAL, INT32,    mgrSilentIntervalMax,   7) \
X(a, STATIC,   OPTIONAL, BOOL,     pointsAlwaysEnabled,   9) \
X(a, STATIC,   OPTIONAL, INT32,    displayBrightness,  10) \
X(a, STATIC,   OPTIONAL, BOOL,     timeModeEnable,   11) \
X(a, STATIC,   OPTIONAL, BOOL,     timeFormat12,     12) \
X(a, STATIC,   OPTIONAL, INT32,    mgrUserActivityTimeout,  13) \
X(a, STATIC,   OPTIONAL, MESSAGE,  silent,           14)
#define Settings_CALLBACK NULL
#define Settings_DEFAULT (const pb_byte_t*)"\x10\x01\x18\x00\x20\x00\x30\x00\x38\x00\x48\x00\x50\x00\x58\x01\x60\x00\x68\xd8\x04\x00"
#define Settings_dnd_MSGTYPE Settings_DND
#define Settings_silent_MSGTYPE Settings_Silent

#define Settings_DND_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     recurring,         1) \
X(a, STATIC,   REQUIRED, INT32,    fromHour,          2) \
X(a, STATIC,   REQUIRED, INT32,    tillHour,          3)
#define Settings_DND_CALLBACK NULL
#define Settings_DND_DEFAULT (const pb_byte_t*)"\x08\x00\x10\x00\x18\x00\x00"

#define Settings_Silent_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     recurring,         1) \
X(a, STATIC,   REQUIRED, INT32,    fromHour,          2) \
X(a, STATIC,   REQUIRED, INT32,    tillHour,          3)
#define Settings_Silent_CALLBACK NULL
#define Settings_Silent_DEFAULT NULL

#define TextData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    modificators,      1) \
X(a, STATIC,   REQUIRED, BYTES,    text,              2)
#define TextData_CALLBACK NULL
#define TextData_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

#define Timer_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    countdown,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  intervals,         2) \
X(a, STATIC,   REPEATED, MESSAGE,  finalText,         3)
#define Timer_CALLBACK NULL
#define Timer_DEFAULT (const pb_byte_t*)"\x08\x00\x00"
#define Timer_intervals_MSGTYPE Timer_Interval
#define Timer_finalText_MSGTYPE TextData

#define Timer_Interval_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  text,              1) \
X(a, STATIC,   REQUIRED, INT32,    duration,          2) \
X(a, STATIC,   OPTIONAL, INT32,    countdown,         3)
#define Timer_Interval_CALLBACK NULL
#define Timer_Interval_DEFAULT (const pb_byte_t*)"\x10\x00\x18\x00\x00"
#define Timer_Interval_text_MSGTYPE TextData

#define AlarmData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           2) \
X(a, STATIC,   OPTIONAL, INT32,    days,              3) \
X(a, STATIC,   REQUIRED, MESSAGE,  time,              4) \
X(a, STATIC,   REQUIRED, UENUM,    sound,             5) \
X(a, STATIC,   REPEATED, MESSAGE,  text,              6)
#define AlarmData_CALLBACK NULL
#define AlarmData_DEFAULT (const pb_byte_t*)"\x10\x01\x18\x00\x00"
#define AlarmData_time_MSGTYPE AlarmData_Time
#define AlarmData_text_MSGTYPE TextData

#define AlarmData_Time_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    hours,             1) \
X(a, STATIC,   REQUIRED, INT32,    minutes,           2)
#define AlarmData_Time_CALLBACK NULL
#define AlarmData_Time_DEFAULT (const pb_byte_t*)"\x08\x00\x10\x00\x00"

#define Alarms_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  alarm,             1)
#define Alarms_CALLBACK NULL
#define Alarms_DEFAULT NULL
#define Alarms_alarm_MSGTYPE AlarmData

#define ForecastScene_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT64,    timestamp,         1) \
X(a, STATIC,   OPTIONAL, UINT32,   doNotChange,       2) \
X(a, STATIC,   REQUIRED, INT32,    maxColor,          4) \
X(a, STATIC,   REQUIRED, INT32,    minColor,          5) \
X(a, STATIC,   REQUIRED, INT32,    max,               6) \
X(a, STATIC,   REQUIRED, INT32,    min,               7) \
X(a, STATIC,   REQUIRED, BYTES,    values,            8) \
X(a, STATIC,   REQUIRED, BYTES,    templateText,      9)
#define ForecastScene_CALLBACK NULL
#define ForecastScene_DEFAULT (const pb_byte_t*)"\x10\x00\x00"

#define AppointmentsScene_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT64,    timestamp,         1) \
X(a, STATIC,   REQUIRED, BYTES,    appointmentData,   2) \
X(a, STATIC,   REPEATED, MESSAGE,  appointmentNames,   3) \
X(a, STATIC,   REQUIRED, UENUM,    notify,            6) \
X(a, STATIC,   REQUIRED, UENUM,    sound,             7)
#define AppointmentsScene_CALLBACK NULL
#define AppointmentsScene_DEFAULT NULL
#define AppointmentsScene_appointmentNames_MSGTYPE TextData

extern const pb_msgdesc_t CustomScene_msg;
extern const pb_msgdesc_t CustomScene_Object_msg;
extern const pb_msgdesc_t CustomScene_Object_AreaAnimationData_msg;
extern const pb_msgdesc_t CustomScene_Object_AreaAnimationData_LightFlashData_msg;
extern const pb_msgdesc_t CustomScene_Object_AreaAnimationData_PulseData_msg;
extern const pb_msgdesc_t CustomScene_Object_AreaAnimationData_WaveData_msg;
extern const pb_msgdesc_t CustomScene_Object_CmdData_msg;
extern const pb_msgdesc_t CustomScene_Object_FillData_msg;
extern const pb_msgdesc_t CustomScene_Object_GifData_msg;
extern const pb_msgdesc_t CustomScene_Object_MovingBarData_msg;
extern const pb_msgdesc_t CustomScene_Object_WeatherData_msg;
extern const pb_msgdesc_t Notice_msg;
extern const pb_msgdesc_t Segments_msg;
extern const pb_msgdesc_t Segments_Segment_msg;
extern const pb_msgdesc_t Settings_msg;
extern const pb_msgdesc_t Settings_DND_msg;
extern const pb_msgdesc_t Settings_Silent_msg;
extern const pb_msgdesc_t TextData_msg;
extern const pb_msgdesc_t Timer_msg;
extern const pb_msgdesc_t Timer_Interval_msg;
extern const pb_msgdesc_t AlarmData_msg;
extern const pb_msgdesc_t AlarmData_Time_msg;
extern const pb_msgdesc_t Alarms_msg;
extern const pb_msgdesc_t ForecastScene_msg;
extern const pb_msgdesc_t AppointmentsScene_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CustomScene_fields &CustomScene_msg
#define CustomScene_Object_fields &CustomScene_Object_msg
#define CustomScene_Object_AreaAnimationData_fields &CustomScene_Object_AreaAnimationData_msg
#define CustomScene_Object_AreaAnimationData_LightFlashData_fields &CustomScene_Object_AreaAnimationData_LightFlashData_msg
#define CustomScene_Object_AreaAnimationData_PulseData_fields &CustomScene_Object_AreaAnimationData_PulseData_msg
#define CustomScene_Object_AreaAnimationData_WaveData_fields &CustomScene_Object_AreaAnimationData_WaveData_msg
#define CustomScene_Object_CmdData_fields &CustomScene_Object_CmdData_msg
#define CustomScene_Object_FillData_fields &CustomScene_Object_FillData_msg
#define CustomScene_Object_GifData_fields &CustomScene_Object_GifData_msg
#define CustomScene_Object_MovingBarData_fields &CustomScene_Object_MovingBarData_msg
#define CustomScene_Object_WeatherData_fields &CustomScene_Object_WeatherData_msg
#define Notice_fields &Notice_msg
#define Segments_fields &Segments_msg
#define Segments_Segment_fields &Segments_Segment_msg
#define Settings_fields &Settings_msg
#define Settings_DND_fields &Settings_DND_msg
#define Settings_Silent_fields &Settings_Silent_msg
#define TextData_fields &TextData_msg
#define Timer_fields &Timer_msg
#define Timer_Interval_fields &Timer_Interval_msg
#define AlarmData_fields &AlarmData_msg
#define AlarmData_Time_fields &AlarmData_Time_msg
#define Alarms_fields &Alarms_msg
#define ForecastScene_fields &ForecastScene_msg
#define AppointmentsScene_fields &AppointmentsScene_msg

/* Maximum encoded size of messages (where known) */
#define AlarmData_Time_size                      22
#define AlarmData_size                           319
#define Alarms_size                              2576
#define AppointmentsScene_size                   1650
#define CustomScene_Object_AreaAnimationData_LightFlashData_size 13
#define CustomScene_Object_AreaAnimationData_PulseData_size 22
#define CustomScene_Object_AreaAnimationData_WaveData_size 11
#define CustomScene_Object_AreaAnimationData_size 318
#define CustomScene_Object_CmdData_size          34
#define CustomScene_Object_FillData_size         528
#define CustomScene_Object_GifData_size          24
#define CustomScene_Object_MovingBarData_size    26
#define CustomScene_Object_WeatherData_size      15
#define CustomScene_Object_size                  1267
#define CustomScene_size                         20320
#define ForecastScene_size                       177
#define GLANCE_PB_H_MAX_SIZE                     CustomScene_size
#define Notice_size                              286
#define Segments_Segment_size                    291
#define Segments_size                            4706
#define Settings_DND_size                        24
#define Settings_Silent_size                     24
#define Settings_size                            110
#define TextData_size                            68
#define Timer_Interval_size                      302
#define Timer_size                               2731

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
